version: "2"
services:
  vtiger:
    build: .
    environment:
      - DB_HOSTNAME=mariadb
      - DB_NAME=vtiger
      - DB_USERNAME=vtiger_user
      - DB_PASSWORD=pwd
    ports:
      - "40080:80"
    links:
      - mariadb
    restart: "no"
    # volumes:
    #   - ./vtigercrm:/var/www/html:rw

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vtiger
      - MYSQL_USER=vtiger_user
      - MYSQL_PASSWORD=pwd
    restart: "no"
    ports:
      - 13306:3306
